apiVersion: v1
kind: Service
metadata:
  name: recipebox-staging
  namespace: colossus-recipebox-staging
  labels:
    app: recipebox-staging
    managed-by: colossus
spec:
  type: ClusterIP
  selector:
    app: recipebox-staging
  ports:
    - port: 80
      targetPort: 80
